FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y install wget

WORKDIR /usr/src

RUN wget https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.2.0/polkadot
RUN wget https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.2.0/polkadot-execute-worker
RUN wget https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-v1.2.0/polkadot-prepare-worker

RUN chmod +x polkadot
RUN chmod +x polkadot-execute-worker
RUN chmod +x polkadot-prepare-worker


EXPOSE 30333

CMD ["./polkadot", "--dev", "--port", "30333"]